force-app/main/default/objects/DoctorList__c/DoctorList__c.object-meta.xml
<CustomObject>
    <label>DoctorList</label>
    <nameField>
        <label>D_First_Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DoctorLists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PAdmission__c/PAdmission__c.object-meta.xml
<CustomObject>
    <label>PAdmission</label>
    <nameField>
        <displayFormat>PA-{000}</displayFormat>
        <label>PAdmissionNo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PAdmissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PAdmission__c/fields/BedNo__c.field-meta.xml
<CustomField>
    <fullName>BedNo__c</fullName>
    <label>BedNo</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PAdmission__c/fields/PA_Name__c.field-meta.xml
<CustomField>
    <fullName>PA_Name__c</fullName>
    <label>PA_Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PAdmission__c/fields/PAge__c.field-meta.xml
<CustomField>
    <fullName>PAge__c</fullName>
    <label>PAge</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PAdmission__c/fields/PaymentStatus__c.field-meta.xml
<CustomField>
    <fullName>PaymentStatus__c</fullName>
    <label>PaymentStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Partial Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PAdmission__c/fields/PDOB__c.field-meta.xml
<CustomField>
    <fullName>PDOB__c</fullName>
    <label>PDOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PAdmission__c/fields/PGender__c.field-meta.xml
<CustomField>
    <fullName>PGender__c</fullName>
    <label>PGender</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PAdmission__c/fields/PPhoneNo__c.field-meta.xml
<CustomField>
    <fullName>PPhoneNo__c</fullName>
    <label>PPhoneNo</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/PAdmission__c/fields/ReferedBy__c.field-meta.xml
<CustomField>
    <fullName>ReferedBy__c</fullName>
    <label>DoctorList</label>
    <referenceTo>DoctorList__c</referenceTo>
    <relationshipLabel>PAdmissions</relationshipLabel>
    <relationshipName>PAdmissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AddmissionController.cls
/**
 * @description       : 
 * @author            : Naushad Ali
 * @group             : 
 * @last modified on  : 12-15-2022
 * @last modified by  : Naushad Ali
**/
public class AddmissionController {
    
    @AuraEnabled(Cacheable=true)
    public static List<PAdmission__c> getAdmissionList()
    {
        return [select Id,PA_Name__c,Name,Patient_Email__c,PaymentStatus__c,PDOB__c,
                 BedNo__c,PGender__c,ReferedBy__c from PAdmission__c ];
    }
    
    @AuraEnabled(Cacheable=true)
    public static List<PAdmission__c> getAdmissionListByName(string pName)
    {
        List<PAdmission__c> admislist;
        if(pName.length()==0)
        {
            admislist=[select Id,PA_Name__c,Name,Patient_Email__c,PaymentStatus__c,PDOB__c,
                 BedNo__c,PAge__c,PGender__c,PPhoneNo__c,ReferedBy__r.Name from PAdmission__c  order by BedNo__c ];

        }
        else {
          admislist = [select Id,PA_Name__c,Name,Patient_Email__c,PaymentStatus__c,PDOB__c,
                 BedNo__c,PAge__c,PGender__c,PPhoneNo__c,ReferedBy__r.Name from PAdmission__c  where PA_Name__c=:pName  order by BedNo__c];
        }
        return admislist;
    }
    
    @AuraEnabled
    public static PAdmission__c createAddmission(PAdmission__c AdmissionObj)
    {
        PAdmission__c newAdd;
        try
        {
			insert   AdmissionObj ;
            newAdd=AdmissionObj;
           
        }
        catch(Exception ex)
        {
            //system.debug(ex.getMessage());
            newAdd=null;
            throw new AuraHandledException(ex.getMessage());
        }
        return newAdd;
    }


    @AuraEnabled(Cacheable=true)
    public static Integer TotalRecords()
    {
        return [select count() from PAdmission__c];
    }

    @AuraEnabled(Cacheable=true)
    public static List<PAdmission__c> getAdmissionByPage(Integer v_Offset,Integer v_pagesize)
    {
        return [select Id,PA_Name__c,Name,Patient_Email__c,PaymentStatus__c,PDOB__c,
                 BedNo__c,PGender__c,ReferedBy__c from PAdmission__c limit: v_pagesize OFFSET : v_Offset ];
    }
    

    @AuraEnabled
    public static Integer getNext(Integer v_OffSet, Integer v_pageSize)
    {
       if(v_OffSet==null)
       {
        v_OffSet=2;
       }
       else 
       {
        v_OffSet= 4;

       }
        return v_OffSet;
    }

    @AuraEnabled(cacheable=true)
    public static Integer getPrevious(Integer v_OffSet, Integer v_pageSize)
    {
        Integer offset1=v_OffSet;
        Integer pagesize=v_pageSize;
        Integer NewOffSet=Integer.valueOf(offset1)+ Integer.valueOf(pagesize);
       
        //v_OffSet-=v_pageSize;
        return NewOffSet;
    }

    

}