force-app/main/default/objects/DoctorList__c/DoctorList__c.object-meta.xml
<CustomObject>
    <label>DoctorList</label>
    <nameField>
        <label>D_First_Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DoctorLists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P_Persciption__c/P_Persciption__c.object-meta.xml
<CustomObject>
    <label>P_Persciption</label>
    <nameField>
        <label>P_Persciption Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P_Persciptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P_Persciption__c/fields/P_Type__c.field-meta.xml
<CustomField>
    <fullName>P_Type__c</fullName>
    <label>P_Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lab Test</fullName>
            </value>
            <value>
                <fullName>Xray</fullName>
            </value>
            <value>
                <fullName>Externa Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/P_Persciption__c/fields/Pat_Perscription__c.field-meta.xml
<CustomField>
    <fullName>Pat_Perscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Perscrption provided by Doctor</description>
    <label>PerscriptionMaster</label>
    <referenceTo>PerscriptionMaster__c</referenceTo>
    <relationshipLabel>P_Persciptions</relationshipLabel>
    <relationshipName>P_Persciptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P_Persciption__c/fields/PatientID__c.field-meta.xml
<CustomField>
    <fullName>PatientID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PAdmission</label>
    <referenceTo>PAdmission__c</referenceTo>
    <relationshipLabel>P_Persciptions</relationshipLabel>
    <relationshipName>P_Persciptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P_Persciption__c/fields/PerAmt__c.field-meta.xml
<CustomField>
    <fullName>PerAmt__c</fullName>
    <formula>PerQty__c  *  Pat_Perscription__r.PerRate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PerAmt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_Persciption__c/fields/PerQty__c.field-meta.xml
<CustomField>
    <fullName>PerQty__c</fullName>
    <label>PerQty</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/P_Persciption__c/fields/PreferedBy__c.field-meta.xml
<CustomField>
    <fullName>PreferedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PreferedBy</label>
    <referenceTo>DoctorList__c</referenceTo>
    <relationshipLabel>P_Persciptions</relationshipLabel>
    <relationshipName>P_Persciptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PAdmission__c/PAdmission__c.object-meta.xml
<CustomObject>
    <label>PAdmission</label>
    <nameField>
        <displayFormat>PA-{000}</displayFormat>
        <label>PAdmissionNo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PAdmissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PAdmission__c/fields/PA_Name__c.field-meta.xml
<CustomField>
    <fullName>PA_Name__c</fullName>
    <label>PA_Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PAdmission__c/fields/PPhoneNo__c.field-meta.xml
<CustomField>
    <fullName>PPhoneNo__c</fullName>
    <label>PPhoneNo</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/PAdmission__c/fields/ReferedBy__c.field-meta.xml
<CustomField>
    <fullName>ReferedBy__c</fullName>
    <label>DoctorList</label>
    <referenceTo>DoctorList__c</referenceTo>
    <relationshipLabel>PAdmissions</relationshipLabel>
    <relationshipName>PAdmissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PerscriptionMaster__c/PerscriptionMaster__c.object-meta.xml
<CustomObject>
    <label>PerscriptionMaster</label>
    <nameField>
        <label>PerscriptionMaster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PerscriptionMasters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PerscriptionMaster__c/fields/PerCode__c.field-meta.xml
<CustomField>
    <fullName>PerCode__c</fullName>
    <label>PerCode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PerscriptionMaster__c/fields/PerRate__c.field-meta.xml
<CustomField>
    <fullName>PerRate__c</fullName>
    <label>PerRate</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PerscriptionMaster__c/fields/PerscriptionName__c.field-meta.xml
<CustomField>
    <fullName>PerscriptionName__c</fullName>
    <label>PerscriptionName</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PatientPrescriptionControllerTEST.cls
@istest
public class PatientPrescriptionControllerTEST {
    
    
    @testSetup static void setUpdata()
    {
      
        PerscriptionMaster__c perMaster= new PerscriptionMaster__c(PerscriptionName__c='Dolo-500',PerCode__c='D-100',PerRate__c=100.20);
        Database.SaveResult dsr;
        dsr=Database.insert(PerMaster,false);
        DoctorList__c docList=new DoctorList__c(Name='Dr.KC',Last_Name__c='Singh');
        insert docList;
        
        PAdmission__c patObj = new PAdmission__c(PA_Name__c='TestPatient',PPhoneNo__c='12345',ReferedBy__c=docList.id);
        insert patObj;
        
        PAdmission__c patObj1 = new PAdmission__c(PA_Name__c='TestPatient1',PPhoneNo__c='123456',ReferedBy__c=docList.id);
        insert patObj1;
        
         PAdmission__c patObj2 = new PAdmission__c(PA_Name__c='TestPatient3',PPhoneNo__c='1234567',ReferedBy__c=docList.id);
        insert patObj2;
        
        P_Persciption__c  patperscription=new P_Persciption__c(
            Name='TestPersciption',PatientID__c=patObj.Id,PreferedBy__c=patObj.ReferedBy__c,
                                                            PerQty__c=2,Pat_Perscription__c=perMaster.Id);
        
        insert patperscription;
        
         P_Persciption__c  patperscription1=new P_Persciption__c(
            Name='TestPersciption1',PatientID__c=patObj.Id,PreferedBy__c=patObj.ReferedBy__c,
                                                            PerQty__c=2,Pat_Perscription__c=perMaster.Id);
        
        insert patperscription1;
        
        //Second Patient Perscirption
        P_Persciption__c  patperscription21=new P_Persciption__c(
            Name='TestPersciption',PatientID__c=patObj1.Id,PreferedBy__c=patObj.ReferedBy__c,
                                                            PerQty__c=2,Pat_Perscription__c=perMaster.Id);
        
        insert patperscription21;
        
         P_Persciption__c  patperscription22=new P_Persciption__c(
            Name='TestPersciption1',PatientID__c=patObj1.Id,PreferedBy__c=patObj.ReferedBy__c,
                                                            PerQty__c=2,Pat_Perscription__c=perMaster.Id);
        
        insert patperscription22;
        
        
        

        
    }
    
    
    private static testMethod void getPrescriptionMasterTest()
    {
         List<PerscriptionMaster__c> perMasList=new List<PerscriptionMaster__c>();
        List<PerscriptionMaster__c> perMasListall=new List<PerscriptionMaster__c>();
         Test.startTest();
         perMasList= PatientPrescriptionController.getPrescriptionMaster('Dol');
         perMasListall= PatientPrescriptionController.getPrescriptionMaster('');
          Test.stopTest();
         system.assertNotEquals(0, perMasList.size());
         system.assertNotEquals(0, perMasListall.size());
        
    }
    
    private static testMethod void updatePatientAmtTest()
    {
        List<PAdmission__c> patientList= [select Id from PAdmission__c];
        //List<P_Persciption__c> persAmt= [select PatientID__c,PerAmt__c from P_Persciption__c];
        
        system.debug(patientList.size());
        //system.debug(persAmt);
        List<Id>  pateientIds =new List<Id>();
        for(PAdmission__c pa:patientList)
        {
            pateientIds.add(pa.Id);
        }
        //List<Id> patientIds=new list<Id>();
       // patientIds=[select Id from PAdmission__c where PA_Name__c=:'TestPatient'];
        Test.startTest();
        PatientPrescriptionController.updatePatientAmt(pateientIds);
       // update patientList;
        Test.stopTest();
        
    }
    
    private static testMethod void updatePatientAmtwithAggregateTest()
    {
        
        List<PAdmission__c> patientList= [select Id from PAdmission__c];
       List<Id>  pateientIds =new  List<Id>();
        for(PAdmission__c pa:patientList)
        {
            pateientIds.add(pa.Id);
        }
        
          
       // patientIds=[select Id from PAdmission__c where PA_Name__c=:'TestPatient'];
        Test.startTest();
        PatientPrescriptionController.updatePatientAmtwithAggregate(pateientIds);
        //update patientList;
        Test.stopTest();
    }
    
    private static testMethod void insertPerscriptionTEST()
    { 
         P_Persciption__c patPerciption= [SELECT Name,Pat_Perscription__c,PerQty__c,PerAmt__c, P_Type__c,PatientID__c, PreferedBy__c
                                          FROM P_Persciption__c limit 1];
         
         List<P_Persciption__c> newperList= new List<P_Persciption__c>();
         List<P_Persciption__c> blankperList=null;
         for(Integer count=0;count<5;count++)
         {
             P_Persciption__c perscription =new P_Persciption__c();
             perscription.Name=patPerciption.Name+count;
             perscription.Pat_Perscription__c=patPerciption.Pat_Perscription__c;
             perscription.PerQty__c=count;
             perscription.PatientID__c=patPerciption.PatientID__c;
             perscription.PreferedBy__c=patPerciption.PreferedBy__c;
             newperList.add(perscription);
         }
        
         boolean successresult;
         boolean falseresult;
         
         try
         {
         Test.startTest();
         successresult=PatientPrescriptionController.insertPerscription(newperList);
         falseresult=PatientPrescriptionController.insertPerscription(blankperList);
      
         Test.stopTest();
         system.assertEquals(true, successresult);
         system.assertEquals(false, falseresult);
        
         }
        catch(Exception ex)
        {
            system.assertEquals(ex.getMessage(), ex.getMessage());
            
        }
        
     
        
    }
    
    
    private static testMethod void upsertPatientPerscirptionTest()
    {
        PAdmission__c patientDetail=[select Id from PAdmission__c where PA_Name__c=:'TestPatient' limit 1];
        List<P_Persciption__c> patperList=[SELECT Name,Pat_Perscription__c,PerQty__c,PerAmt__c, P_Type__c,PatientID__c, PreferedBy__c
                                          FROM P_Persciption__c where PatientID__c=:patientDetail.Id ];
        for(P_Persciption__c per:patperList)
        {
            per.PerQty__c++;
            
        }
        
         P_Persciption__c perscription =new P_Persciption__c();
         perscription.Name=patperList[0].Name;
         perscription.Pat_Perscription__c=patperList[0].Pat_Perscription__c;
         perscription.PerQty__c=10;
         perscription.PatientID__c=patperList[0].PatientID__c;
         perscription.PreferedBy__c=patperList[0].PreferedBy__c;
         P_Persciption__c perscriptionblank=new P_Persciption__c();
        
        patperList.add(perscription);
        patperlist.add(perscriptionblank);
        boolean result;
       try
       {
        Test.startTest();
         PatientPrescriptionController.mimicException=true;
        result=PatientPrescriptionController.upsertPatientPerscirption(patperList);
        Test.stopTest();
        system.assertEquals(true,result);
       }
       catch(Exception ex)
       {
           system.assertEquals(false, result);
           system.assertEquals('Error in list', ex.getMessage());
          
       }
    }
    
    private static testMethod void getPatientPrescriptionbyIdTEST()
    {
        PAdmission__c patientDetail=[select Id from PAdmission__c where PA_Name__c=:'TestPatient' limit 1];
        List<P_Persciption__c> patperList=[SELECT Name,Pat_Perscription__c,PerQty__c,PerAmt__c, P_Type__c,PatientID__c, PreferedBy__c
                                          FROM P_Persciption__c where PatientID__c=:patientDetail.Id ];
        Test.startTest();
        List<P_Persciption__c> expectedList= PatientPrescriptionController.getPatientPrescriptionbyId(patientDetail.Id);
        Test.stopTest();
        system.assertEquals(patperList.size(), expectedList.size());
        
    }
    
    private static testMethod void deletePatientPerscirptionTEST()
    {
        PAdmission__c patientDetail=[select Id from PAdmission__c where PA_Name__c=:'TestPatient' limit 1];
        List<P_Persciption__c> patperList=[SELECT Id,Name,Pat_Perscription__c,PerQty__c,PerAmt__c, P_Type__c,PatientID__c, PreferedBy__c
                                          FROM P_Persciption__c where PatientID__c=:patientDetail.Id ];
        List<P_Persciption__c> patListblank=new List<P_Persciption__c>();
        boolean delResult;
        boolean errorResult;
        Test.startTest();
        try
        {
        delResult = PatientPrescriptionController.deletePatientPerscirption(patperList);
        errorResult = PatientPrescriptionController.deletePatientPerscirption(patListblank);
        }
        catch(DMLException ex)
        {
            System.assertEquals(ex.getMessage(), ex.getMessage());
        }
        Test.stopTest();
       
        
        system.assertEquals(true, delResult);
        system.assertEquals(false, errorResult);
        
    }

}