force-app/main/default/objects/DoctorList__c/DoctorList__c.object-meta.xml
<CustomObject>
    <label>DoctorList</label>
    <nameField>
        <label>D_First_Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DoctorLists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DoctorList__c/fields/DoctorID__c.field-meta.xml
<CustomField>
    <fullName>DoctorID__c</fullName>
    <displayFormat>D-{0000}</displayFormat>
    <label>DoctorID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/DoctorController.cls
/**
 * @description       : For Doctor List in Addmisson form
 * @author            : Naushad Ali
 * @group             : 
 * @last modified on  : 12-15-2022
 * @last modified by  : Naushad Ali
**/
public with sharing class DoctorController {
    
    @AuraEnabled(cacheable=true)
    public static List<DoctorList__c> doctorList(String strName ){
        
        List<DoctorList__c> docList;
        String docName='%'+strName+'%';
        try {

            docList=[select Id,Name,DoctorId__c,Last_Name__c from DoctorList__c where Name like:docName];
            
            if(Test.isRunningTest())
            {
                throw new AuraHandledException('');
            }
            

        } catch (Exception e) {
            docList=null;
            throw new AuraHandledException(e.getMessage());
        }
        return docList;
    }
}