force-app/main/default/objects/DoctorList__c/DoctorList__c.object-meta.xml
<CustomObject>
    <label>DoctorList</label>
    <nameField>
        <label>D_First_Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DoctorLists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DoctorList__c/fields/DoctorID__c.field-meta.xml
<CustomField>
    <fullName>DoctorID__c</fullName>
    <displayFormat>D-{0000}</displayFormat>
    <label>DoctorID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/PAdmission__c/PAdmission__c.object-meta.xml
<CustomObject>
    <label>PAdmission</label>
    <nameField>
        <displayFormat>PA-{000}</displayFormat>
        <label>PAdmissionNo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PAdmissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PAdmission__c/fields/PA_Name__c.field-meta.xml
<CustomField>
    <fullName>PA_Name__c</fullName>
    <label>PA_Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PAdmission__c/fields/ReferedBy__c.field-meta.xml
<CustomField>
    <fullName>ReferedBy__c</fullName>
    <label>DoctorList</label>
    <referenceTo>DoctorList__c</referenceTo>
    <relationshipLabel>PAdmissions</relationshipLabel>
    <relationshipName>PAdmissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DoctorPatientController.cls
public with sharing class DoctorPatientController {
    public DoctorPatientController() {

    }

    @AuraEnabled(cacheable=true)
    public static List<DoctorList__c> getDoctorList(){

        return [select DoctorID__c,Name,Last_Name__c from DoctorList__c];
       
    }


    @AuraEnabled(cacheable=true)
    public static list<PAdmission__c> findPAdmissionByDoctorId(string DoctorId)
    {
        return [select Name,PA_Name__c from PAdmission__c where ReferedBy__c=:DoctorId];

    }
    
}