force-app/main/default/objects/PAdmission__c/PAdmission__c.object-meta.xml
<CustomObject>
    <label>PAdmission</label>
    <nameField>
        <displayFormat>PA-{000}</displayFormat>
        <label>PAdmissionNo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PAdmissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PAdmission__c/fields/PA_Name__c.field-meta.xml
<CustomField>
    <fullName>PA_Name__c</fullName>
    <label>PA_Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PAdmission__c/fields/PPhoneNo__c.field-meta.xml
<CustomField>
    <fullName>PPhoneNo__c</fullName>
    <label>PPhoneNo</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/PAdmission__c/fields/ReferedBy__c.field-meta.xml
<CustomField>
    <fullName>ReferedBy__c</fullName>
    <label>DoctorList</label>
    <referenceTo>DoctorList__c</referenceTo>
    <relationshipLabel>PAdmissions</relationshipLabel>
    <relationshipName>PAdmissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/padmissiontri_test.cls
@isTest
public class padmissiontri_test {
    
    @testSetup static void setupmethod()
    {
        String PName='Ramesh Kumar';
        String Phone='1235456';
        PAdmission__c padd=new PAdmission__c();
        padd.PA_Name__c=PName;
        padd.ReferedBy__c='a0W2v00001GhxZVEAZ';
        padd.PPhoneNo__c=Phone;
        insert padd;
    }
    
    public static testMethod void Testpadmissiontri_test()
    {
        string addError;
        String PName='Ramesh Kumar';
        String Phone='1235456';
        List<PAdmission__c> dupAdd1=[select Id,PA_Name__C,PPhoneNo__c from PAdmission__c];
        system.debug(dupAdd1.size());
        PAdmission__c padd=new PAdmission__c();
        padd.PA_Name__c=PName;
        padd.ReferedBy__c='a0W2v00001GhxZVEAZ';
        padd.PPhoneNo__c=Phone;
       
        if(dupAdd1.size() < 1)
        {
            
            system.assertEquals(0, dupAdd1.size());
            Test.startTest();
            insert padd; 
            //system.debug('Record Inserted');
            Test.stopTest();
        }
        else
        {
            addError='Existing';
            //system.debug('Duplicate Exists');
        }
        
       System.assertEquals('Existing', addError);
      
        
    }

}